---
openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/EVGENYSEVOSTIANOV_1/mobileapplication/1.0.0
info:
  description: API для взаимодействия клиента с API шлюзом.
  version: "1.0.0"
  title: Helpful Driver API
paths: 
  /sms_auth:
    post:
      summary: Запрос на получение SMS c одноразовым паролем
      description: Отправить запрос на получение SMS c одноразовым паролем
      requestBody:
        content:
          application|json:
            schema:
              type: object
              properties:
                phone_number:
                  type: integer
                  example: 79880000000
      responses:
        '201':
          description: OK
          content:
            application|json:
              schema:
                type: object
                properties:
                  sucess:
                    type: boolean
                    example: true
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
  /sms_auth/{token}:
    put:
      summary: Запрос на проверку одноразового пароля 
      description: Отправить запрос на проверку одноразового пароля
      parameters:
        - name: token
          in: path
          description: Токен
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
      requestBody:
        content:
          application|json:
            schema:
              type: object
              properties:
                sms_code:
                  type: integer
                  example: 1234
      responses:
        '204':
          description: OK
  /tasks:
    get:
      summary:  Запрос на получение списка заданий
      description:  Запрос на получение информации о доступных заданиях
      parameters:
        - name: token
          in: header
          description: Токен
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
        - name: role
          in: query
          description: Фильтр
          required: false
          explode: true
          schema:
            type: string
            default: none
            enum:
              - none
              - initiator
              - executor
        - name: nearby
          in: query
          description: Фильтр
          required: false
          explode: true
          schema:
            type: boolean
            default: true
            enum:
              - true
              - false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    task_id:
                      type: string
                      example: 12345
                    type_id:
                      type: string
                      example: 3
                    vehicle_category:
                      type: string
                      example: 2
                    description:
                      type: string
                      minLength: 5
                      maxLength: 100
                      example: Сломал балонник, может есть у кого?
                    region:
                      type: string
                      example: Волгоградская область
                    city:
                      type: string
                      example: Волгоград
                    coordinates:
                      type: integer
                      example: {latitude, longitude}
                    created_at:
                      type: string
                      example: 2023-01-01T09:12:33.001Z
        '400':
          description: Некорректные координаты
    post:
      summary: Запрос на создание задания
      description: Запрос на создание задания
      parameters:
        - name: token
          in: header
          description: Токен
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
      requestBody:
        content:
          application|json:
            schema:
              type: object
              properties:
                    type_id:
                      type: string
                      example: 3
                    vehicle_category:
                      type: string
                      example: 2
                    description:
                      type: string
                      minLength: 5
                      maxLength: 100
                      example: Сломал балонник, может есть у кого?
                    region:
                      type: string
                      example: Волгоградская область
                    city:
                      type: string
                      example: Волгоград
                    coordinates:
                      type: integer
                      example: {latitude, longitude}
      responses:
        '201':
          description: OK
          content:
            application|json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  task_id:
                    type: string
                    example: 9117d0f9-061f-424e-ae50-c23aeae0fc43
  /tasks/{task_id}:
    patch:
      summary: Запрос на изменение статуса задания
      description: Запрос на изменение статуса задания.
      parameters:
        - name: token
          in: header
          description: Токен
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
        - name: task_id
          in: path
          description: ID задания
          required: true
          schema:
            type: string
            example: 8a377ca4-ee44-11ed-a05b-0242ac120003
      requestBody:
        content:
          application|json:
            schema:
              type: object
              properties:
                    status_id:
                      type: string
                      example: 2
      responses:
        '204':
          description: OK
  /bonuses:
    get:
      summary:  Запрос на получение списка доступных бонусов
      description:  Запрос на получение списка доступных бонусов
      parameters:
        - name: token
          in: header
          description: Токен
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MzYxODA4MiwiaWF0IjoxNjgzNjE4MDgyfQ.5o7kzagOaNKDrD2Oo9lqUWaaiuhC8UsCTw_lck0qk1U
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    loyalty_id:
                      type: string
                      example: 4a56fad5-686b-4c12-8bf1-ceebcb679dc3
                    status_id:
                      type: string
                      example: 1
                    description:
                      type: string
                      example: Ваша 5% скидка на заправочных станциях Лукойл
                    href:
                      type: string
                      example: https://auto.lukoil.ru/ru/LUKOILClub/Benefits
